### ISSUE TITLE
Fetch a particular preset filter from the list

### ISSUE THREAD

**Issue by crazyscoop** [dipendra-sharma/flutter_color_filter_extension#1]
Add a name field to [ColorPresetField](https://github.com/dipendra-sharma/flutter_color_filter_extension/blob/e9eb8ccca34ce8adb8fd3db792ac9386de8c1531/lib/src/preset.dart#L4) to retrieve a particular filter.

**Comment by dipendra-sharma** [comment]
Hi @crazyscoop Thanks for posting issue. You can access particular filter by it's name only.  Example is

`ColorFiltersPreset.clarendon()`

If this doesn't solve problem, please explain.
