### ISSUE TITLE
Is this possible to export an image with applied filter?

### ISSUE THREAD

**Issue by Muzammil-Bit** [dipendra-sharma/flutter_color_filter_extension#2]

**Comment by dipendra-sharma** [comment]
Please refer https://pbhoomi190.medium.com/colorfilter-and-repaintboundary-to-apply-filter-and-crop-an-image-in-flutter-e29fe1d02965

**Comment by Muzammil-Bit** [comment]
> Please refer https://pbhoomi190.medium.com/colorfilter-and-repaintboundary-to-apply-filter-and-crop-an-image-in-flutter-e29fe1d02965

Thanks a lot for the link. It is super helpful!!🙌🏻
